export const routes = {
  home: '/',
  catalog: '/catalog',
  discounts: '/discounts',
  about: '/about',
  contact: '/contact',
  category: (slug: string) => `/category/${slug}`,
  product: (slug: string) => `/product/${slug}`,
  cart: '/cart',
  checkout: '/checkout',
  orderSuccess: '/order-success',
  adminLogin: '/admin/login',
  admin: '/admin',
  adminProducts: '/admin/products',
  adminProductNew: '/admin/products/new',
  adminProductEdit: (id: string) => `/admin/products/${id}/edit`,
  adminCategories: '/admin/categories',
  adminOrders: '/admin/orders',
} as const
