import { SITE_NAME } from '@/utils/constants'

export const homeSeo = {
  title: `Official WWII Camouflage and Markings Books`,
  description:
    'Buy hand-drawn WWII reference books by Igor Donchik: Panzer Camouflage, German Military Unit Insignia, and German Military Symbols. Official artist site, shipped from Estonia.',
}

export const storePageCopy = {
  title: 'Store',
  seoTitle: 'WWII Reference Books for Modelers and Historians',
  seoDescription:
    'Shop Igor Donchik’s official WWII art books: panzer camouflage profiles, Wehrmacht unit insignia, and German tactical symbols. Limited print runs, packed in Estonia.',
  description:
    'Every volume on this site is drawn by hand from archival photographs and wartime documents — not generated by AI. Choose a series below, or open a book page for plates, chapter lists, and shipping details.',
  paragraphs: [
    'The store currently lists three ongoing encyclopedias: Panzer Camouflage for armor paint schemes, German Military Unit Insignia for divisional emblems, and German Military Symbols for tactical signs used on vehicles and maps.',
    'Hardcover and softcover references ship from Estonia with Omniva tracking, a rigid carton, and bubble wrap. Selected Panzer Camouflage volumes include collector shipping for €1.',
  ],
}

export const discountsPageCopy = {
  title: 'Discounts',
  seoTitle: 'Sale Copies of WWII Reference Books',
  seoDescription:
    'Discounted Igor Donchik books with minor cover wear. Same interior plates at a lower price. Sale copies are final sale and cannot be returned or exchanged.',
  description:
    'When a cover picks up a small scuff in printing or packing, the volume is offered here instead of being discarded. The plates inside are complete.',
  paragraphs: [
    'Sale copies are sold as-is. By ordering a discounted book you accept minor exterior defects, and the copy cannot be refunded or exchanged.',
    'If you need a pristine cover for a collection, choose the standard edition in the store. If you mainly need the reference plates, a sale copy is the economical way to add the volume to the bench.',
  ],
}

export const aboutPageCopy = {
  title: 'About Igor Donchik Art',
  seoTitle: 'About Igor Donchik | Military Illustrator and WWII Researcher',
  seoDescription:
    'Igor Donchik is a military illustrator reconstructing WWII camouflage, unit insignia, and tactical symbols by hand from archival sources. Official artist website.',
  description:
    `${SITE_NAME} is the official website of the artist behind the Panzer Camouflage, German Military Unit Insignia, and German Military Symbols encyclopedias.`,
  studioTitle: 'A studio built for visual military history',
  studioParagraphs: [
    'Each plate starts with wartime photographs, film stills, and surviving documents. Patterns are compared across sources, then redrawn so modelers and researchers can see camouflage, emblems, and tactical signs with consistent line and color.',
    'The books are printed in limited batches. Orders leave Estonia packed in a cardboard carton with extra wrap and a tracking number. Shipments are not sent to the Russian Federation or Belarus.',
    'Readers who already know the not-TOYS shop will find the same author here — with catalog copy written for this official site, plus the series context, chapter lists, and research notes that belong next to the books.',
  ],
  seriesTitle: 'Three reference series, one research method',
  methodTitle: 'How the reconstructions are made',
  methodParagraphs: [
    'Igor Donchik works as both illustrator and researcher. Vehicle profiles, divisional badges, and map symbols are traced from period evidence rather than invented “box-art” patterns.',
    'Where a photograph is incomplete, the gap is stated in the research rather than filled with guesswork. Unidentified insignia stay unidentified until a better source appears.',
    'No volume in the current catalog is produced with generative AI. The drawings, lettering, and color notes are manual work intended to stay useful on the workbench years after publication.',
  ],
}

export const contactPageCopy = {
  title: 'Contact us',
  seoTitle: 'Contact Igor Donchik Art | Orders and Press',
  seoDescription:
    'Contact Igor Donchik Art in Estonia for book orders, shipping questions, and press. Sales email, studio email, and phone with Omniva dispatch from Uusküla.',
  description: `Write to ${SITE_NAME} for stock, delivery, or research questions. Orders are packed in Estonia and usually leave once a week.`,
  paragraphs: [
    'Use the sales address for shop orders, tracking, and VAT questions. Use the studio address for interviews, licensing, or notes about archival sources.',
    'Please include a phone number in international format (+country code). That number is required by the carrier. EU VAT is added at checkout; outside the EU the listed price is the amount you pay.',
    'Parcels travel with Estonian Omniva, in a rigid box with bubble film and a tracker. We do not dispatch to the Russian Federation or Belarus.',
  ],
  hoursTitle: 'Orders and replies',
  hoursParagraphs: [
    'Because print runs are small and demand is high, packed orders typically leave once per week rather than the same day.',
    'If you are waiting on a coming-soon volume such as Panzer Camouflage V or Unit Insignia II, the product page lists the planned year. We do not take pre-orders until a book is ready to ship.',
  ],
}

export const cartPageCopy = {
  seoTitle: 'Cart',
  seoDescription: `Review WWII reference books in your ${SITE_NAME} cart before checkout.`,
}

export const checkoutPageCopy = {
  seoTitle: 'Checkout',
  seoDescription: `Send a book order request to ${SITE_NAME}. Payments are confirmed separately.`,
}
